spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true  # Enable service discovery
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL of your Eureka server

    gateway:
      routes:
        - id: FLIGHT-SERVICE
          uri: lb://FLIGHT-SERVICE  # The name of the microservice registered in Eureka
          predicates:
            - Path=/flights/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE	  # The name of another microservice
          predicates:
            - Path=/users/**